// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABy2OUbSpLl2xDgg4TcV2n8uJsbktvvdA',
    appId: '1:36430964064:web:65da897287e1b54a8baa05',
    messagingSenderId: '36430964064',
    projectId: 'flutter-project-bd248',
    authDomain: 'flutter-project-bd248.firebaseapp.com',
    storageBucket: 'flutter-project-bd248.firebasestorage.app',
    measurementId: 'G-W4GH8C390H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIE36LYWQ74fErCd1CpWJtZMYopId-Cn8',
    appId: '1:36430964064:android:cb9165c271e11f238baa05',
    messagingSenderId: '36430964064',
    projectId: 'flutter-project-bd248',
    storageBucket: 'flutter-project-bd248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3FOa7lSoVb-StNDtzOOjeUWPaWf8TdLw',
    appId: '1:36430964064:ios:57ac57de1fb0854f8baa05',
    messagingSenderId: '36430964064',
    projectId: 'flutter-project-bd248',
    storageBucket: 'flutter-project-bd248.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );
}
